server:
  port: 8080
  compression:
    enabled: true #Wheter response compression is enabled
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
    min-size-response-time: 1024 # Minimun content-length valur required for compression start.

  undertow:
    threads:
      worker: 64 #Generally, this should be reasonably high, at least 10 per core.
      io: 4 # One I/O thread per CPU core is a reasoble default.

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: true
        connection:
          provider_disable_autocommit: true

    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none